batch_size: 1000
benchmark_dir: /home/hachan/Code/MTAD/benchmark/benchmark_results
data_root: /mnt/c/Users/Hacha/Documents/VHTWork/Datasets/AnomalyDetection/processed_dataset/processed_SMD/
dataset: smd
dataset_id: SMD
device: 0
dim: 38
entities:
- machine-1-1
- machine-1-2
epsilon: 1.0e-10
eval:
  best_params:
    target_direction: max
    target_metric: f1
  metrics:
  - f1
  - delay
  point_adjustment:
  - true
  - false
  pot_params:
    dynamic: false
    level:
    - 0.99
    - 0.98
    - 0.97
    - 0.9
    - 0.8
    q: 0.01
  thresholding:
  - best
  - pot
exp_id: streaming_loda_SMD
histograms_per_batch: 1
memory: 5
model_id: streaming_loda
model_root: /home/hachan/Code/MTAD/benchmark/benchmark_exp_details/SMD/streaming_loda/streaming_loda_SMD
n_histograms: 100
normalize: minmax
nrows: null
padding: 0.1
score_decay: 1.0
standardize_window: true
test_label_postfix: test_label.pkl
test_postfix: test.pkl
train_postfix: train.pkl
update_on_test: true
uptime: 20260919-140436
valid_ratio: 0
