alpha: 0.2
batch_size: 16
benchmark_dir: /home/hachan/Code/MTAD/benchmark/benchmark_results
data_root: /mnt/c/Users/Hacha/Documents/VHTWork/Datasets/AnomalyDetection/processed_dataset/processed_SMD/
dataset: smd
dataset_id: SMD
device: 0
dim: 38
dropout: 0.3
entities:
- machine-1-1
- machine-1-2
eval:
  best_params:
    target_direction: max
    target_metric: f1
  metrics:
  - f1
  - delay
  point_adjustment:
  - true
  - false
  pot_params:
    dynamic: false
    level:
    - 0.99
    - 0.98
    - 0.97
    - 0.9
    - 0.8
    q: 0.01
  thresholding:
  - best
  - pot
exp_id: mtad_gat_SMD
feat_gat_embed_dim: null
forecast_hid_dim: 150
forecast_n_layers: 1
gamma: 1
gru_hid_dim: 150
gru_n_layers: 1
init_lr: 0.0003
kernel_size: 7
model_id: mtad_gat
model_root: /home/hachan/Code/MTAD/benchmark/benchmark_exp_details/SMD/mtad_gat/mtad_gat_SMD
nb_epoch: 10
normalize: minmax
nrows: null
num_workers: 1
recon_hid_dim: 150
recon_n_layers: 1
shuffle: true
stride: 1
test_label_postfix: test_label.pkl
test_postfix: test.pkl
time_gat_embed_dim: null
train_postfix: train.pkl
uptime: 20260915-211428
use_gatv2: true
valid_ratio: 0
window_size: 30
